DELETE FROM horses
WHERE name IN (
  'Jumping Pro 1',
  'Jumping Pro 2',
  'Jumping Pro 3',
  'Jumping Pro 4',
  'Jumping Pro 5',
  'Jumping Pro 6',
  'Jumping Pro 7',
  'Jumping Pro 8',
  'Jumping Pro 9',
  'Jumping Pro 10',
  'Jumping Pro 11',
  'Jumping Pro 12',
  'Jumping Pro 13',
  'Jumping Pro 14',
  'Jumping Pro 15',
  'Jumping Pro 16',
  'Jumping Pro 17',
  'Jumping Pro 18',
  'Jumping Pro 19',
  'Jumping Pro 20',
  'Jumping Pro 21',
  'Jumping Pro 22',
  'Dressage Star 1',
  'Dressage Star 2',
  'Dressage Star 3',
  'Dressage Star 4',
  'Dressage Star 5',
  'Dressage Star 6',
  'Dressage Star 7',
  'Dressage Star 8',
  'Dressage Star 9',
  'Dressage Star 10',
  'Dressage Star 11',
  'Luna - Levisto x Balou du Rouet'
);
